data: ""
folders:
  input : "input"
  output : 
    default: "output"
    queries: "output/queries"
params:
  k: 17
  BF_size: 100
  samples: "truth"
  types: ["raw", "cleaned"]
  genes: ["genes", "test"]
